Repository jenkinsci/license-maven-plugin, pull requests merged in 2023-07, with the labels that each got.

#21 Misc. cleanup
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  Jenkinsfile
  pom.xml
  src/test/java/com/cloudbees/Junit4DummyTest.java
Labels: chore

#24 Publish to repo.jenkins.org, move to Java 11 and change groupId
  .mvn/extensions.xml
  .mvn/maven.config
  pom.xml
Labels: Breaking changes

#25 Enable CD
  .github/release-drafter.yml
  .github/workflows/cd.yml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: Breaking changes

#19 Add prerequisites
  pom.xml
Labels: chore

#27 Fix CD tag template
  pom.xml
Labels: chore

#28 Remove RD template
  .github/release-drafter.yml
Labels: chore

#30 Prevent new high-priority SpotBugs violations from being introduced
  pom.xml
  src/main/java/com/cloudbees/maven/license/CompleterDelegate.java
Labels: internal

#31 Add Maven mojo documentation site
  .github/workflows/site.yml
  pom.xml
  src/site/apt/index.apt
  src/site/site.xml
Labels: documentation

#34 Keep track of updates for maven-fluido-skin
  .github/renovate.json
Labels: chore
